CREATE TABLE MYFRONT_MEMBER(
	memberId VARCHAR2(300),
	memberPw VARCHAR2(300),
	memberName VARCHAR2(300),
	memberEmail VARCHAR2(200),
	CONSTRAINT MYFRONT_PK PRIMARY KEY(memberId)
);

SELECT * FROM MYFRONT_MEMBER;